#!/bin/fish
set items echo " Lock| Suspend| Logout| Reboot| Shutdown"
set result ($items | rofi -sep '|' -dmenu -i -p 'System' -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 5)


switch $result 
case "*Lock"
    i3lock
case "*Logout"
    i3-msg exit
case "*Suspend"
   i3lock && systemctl suspend 
case "*Reboot"
    systemctl reboot
case "*Shutdown"
    systemctl poweroff
end


