#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) i3exit lock ;;
                *Logout) i3exit logout;;
                *Reboot) i3exit reboot ;;
                *Shutdown) i3exit shutdown
            esac
