theme = "mytheme"

[editor]
scroll-lines = 1
cursorline = true
auto-save = false
auto-format = true
completion-trigger-len = 1
true-color = true
color-modes = true
auto-pairs = true
rulers = [100,120]
idle-timeout = 50
shell = ["fish", "-c"]
bufferline = "multiple"

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "spacer", "file-type", "total-line-numbers", "file-encoding"]
center = ["file-modification-indicator","file-name"]
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]

[editor.file-picker]
# hidden = false

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.jump-mode]
dim-during-jump = true
num-chars-before-label = 2
jump-keys = "ntehosia"

[keys.normal.space]
w = ":w"
q = ":bc"
Q = ":q"
# Add semicolumn to the end of the line
";" = [
    "save_selection",
    "goto_line_end",
    ":append-output echo ';'",
    "collapse_selection",
    "delete_selection",
    "jump_backward",
]
F = "file_picker_in_current_buffer_directory" # useful for accessing sibling files rather than a file tree
"." = ":toggle-option file-picker.git-ignore" # toggle seeing files hidden with the .gitignore in file pickers,
"=" = ":format"

[keys.normal]
q = "no_op"
Q = "no_op"
B = "extend_prev_word_start"
W = "extend_next_word_end"
X = "extend_line_above"
";" = "flip_selections"
esc = ["collapse_selection", "keep_primary_selection"]
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
d = ["yank_main_selection_to_clipboard", "delete_selection"]
R = ["replace_selections_with_clipboard"]
pageup = "half_page_up"
pagedown = "half_page_down"


[keys.select]
pageup = "half_page_up"
pagedown = "half_page_down"
y = "yank_main_selection_to_clipboard"
p = "replace_selections_with_clipboard"
d = ["yank_main_selection_to_clipboard", "delete_selection"]

[keys.insert]
"C-space" = "completion"
